### ISSUE TITLE
Homebrew для Brick Game x in 1 (Тетрис) портативок

### ISSUE THREAD

**Issue by jan-kleks** [azya52/microvision#1]
Здрасте! У вас очень классные проекты для ретро портативок и вижу, что вы любите тетрис. А вы когда-нибудь думали о том, чтобы сделать новую игру для приставок Brick Game? Здесь нашел вот такую интересную статью (может она вас тоже заинтересует): 

- Возможный процессор тетриса (Brick Game): https://hype.retroscene.org/blog/1033.html

Портативный бонус))

- Разработка игр для Game & Watch: https://atariage.com/forums/topic/282578-two-new-homebrew-lcd-games-game-watch/
- Homebrew для старых Нокии: https://arkadiusz.wahlig.eu/NokiX.html

**Comment by azya52** [comment]
Здравствуйте!
К сожалению, только увидел ваш комментарий, GitHub почему-то не присылает уведомления о новых Issues.
Проблема с Brick Game в том, что прошивка жестко записана в микроконтроллер и что-то написать для нее без сильной модификации железа не получится( То же самое касается Game & Watch.
